### ISSUE TITLE
Request: option to camelCase the field names

### ISSUE THREAD

**Issue by thevictorlopez** [josdejong/csv42#4]
Hello! First of all, thanks for this great library! 

I've been using csv42 for a project where I need to parse several csv files with headers that contain spaces, e.g.:

```
value one, value two, etc
test, 100.00, foo
test, 200.00, foo 
```

which leads to lots of braces and strings when manipulating the resulting object:

```
console.log(row['value one']);
console.log(row['value two']);
```

I would like to have something slightly more readable and easy to work with like:

```
console.log(row.valueOne);
console.log(row.valueTwo);
```

I'm thinking this could be either an option when calling the parser to always turn the field names into camelCase, or maybe we could provide a function on the options object:

```
const report = csv2json(csv, {
    header: (field) => camelize(field),  // it implies there is a header row in the CSV input
    fields: [],
  });
```

would this be something valuable for the library? if there is interest I could spend some time prototyping a PR for this in the coming weeks

thanks!

**Comment by josdejong** [comment]
Thanks!

You can do that by providing a callback for `fields`, where you can provide a custom `setValue` function:

```js
csv2json(data, {
  fields: (names) =>
    names.map((name) => {
      return { 
        name, 
        setValue: (item, value) => (item[toCamelCase(name)] = value) 
      }
    })
})

function toCamelCase(name) {
  // ...
}
```

**Comment by josdejong** [comment]
👍 

have a nice weekend
