### ISSUE TITLE
Flattening to CSV where source JSON contains '\n' in some value renders ↵ in csv

### ISSUE THREAD

**Issue by lexybarton** [josdejong/csv42#5]
|  |  |
|---|---|
|✒| Hey @josdejong 👋,<br> thank you for your work on csv42, which I value for its' JSON flattening feature, which for me works better then others I tried. Recently I had noticed some wrong CSV being produced with newlines scattered within in the middle of data row. Of course it was an error in my data, which was responsible for the sudden flaws in the CSV files, yet I thing the discovered behaviour is rather unintended.|
---
### Problem description

When flattening a JSON to CSV, where source JSON contains some value containing "**_\n_**", the resulting CSV breaks, due to actual line break rendered in that place.

### Steps to reproduce
on jsoneditoronline.org insert:
```JSON
[{"key1":"This is: \nJSON","key2":42}]
```
then click __`Save ▼`__ and choose __`Export to CSV`__.

### Results
| Expected result | Actual result |
|---|---|
| key1,key1<br>"This is: \nJSON",42 | key1,key1<br>"This is: <br>JSON",42 |

**Comment by josdejong** [comment]
> thank you for your work on csv42, which I value for its' JSON flattening feature, which for me works better then others I tried. 

Thanks, good to hear :)

In CSV, a newline character must not be escaped as `\n` like JSON, so I think the actual result is correct. When you open the actual result in Excel or Google Sheets, it renders as expected with a newline between "This is: " and "JSON".

See section 2.6 and 2.7 of the CSV standard https://www.rfc-editor.org/rfc/rfc4180: 

```
   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx

   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```

So, only double quotes need to be escaped, but not CRLF or anything else.

**Comment by lexybarton** [comment]
It took me a while to get my head around it. But in deed there can be line breaks... Thank you for your time and for teaching me a thing. 🙏 Best regards from Prague, Ondrej

**Comment by josdejong** [comment]
👍 you're welcome.
